export const SEARCH_MODULES = [
  {
    id: "package",
    label: "Packages",
    shortLabel: "Packages",
    icon: "fi-rr-umbrella-beach",
    iconBg: "bg-primary-50",
    iconColor: "text-primary-600",
    activeText: "text-primary-700",
    searchBtn: "bg-primary-600 hover:bg-primary-700",
    enabled: true,
  },
  {
    id: "schedule",
    label: "Scheduled",
    shortLabel: "Scheduled",
    icon: "fi-rr-calendar",
    iconBg: "bg-sky-50",
    iconColor: "text-sky-600",
    activeText: "text-sky-700",
    searchBtn: "bg-sky-600 hover:bg-sky-700",
    enabled: true,
  },
  {
    id: "activities",
    label: "Activities",
    shortLabel: "Activities",
    icon: "fi-rr-hiking",
    iconBg: "bg-emerald-50",
    iconColor: "text-emerald-600",
    activeText: "text-emerald-700",
    searchBtn: "bg-emerald-600 hover:bg-emerald-700",
    enabled: true,
  },
  {
    id: "events",
    label: "Events",
    shortLabel: "Events",
    icon: "fi-rr-glass-cheers",
    iconBg: "bg-rose-50",
    iconColor: "text-rose-600",
    activeText: "text-rose-700",
    searchBtn: "bg-rose-600 hover:bg-rose-700",
    enabled: true,
  },
  {
    id: "attractions",
    label: "Attractions",
    shortLabel: "Attractions",
    icon: "fi-rr-ferris-wheel",
    iconBg: "bg-amber-50",
    iconColor: "text-amber-600",
    activeText: "text-amber-700",
    searchBtn: "bg-amber-600 hover:bg-amber-700",
    enabled: true,
  },
  {
    id: "rentals",
    label: "Rentals",
    shortLabel: "Rentals",
    icon: "fi-rr-car-side",
    iconBg: "bg-indigo-50",
    iconColor: "text-indigo-600",
    activeText: "text-indigo-700",
    searchBtn: "bg-indigo-600 hover:bg-indigo-700",
    enabled: true,
  },
];
